# Generated by Django 2.0.1 on 2018-01-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('occur', models.PositiveIntegerField(default=0)),
                ('arrest', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('area', 'location'),
            },
        ),
    ]
