# Generated by Django 2.0.1 on 2018-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
