from .board import BoardList, BoardDetail, BoardAnalizeByBoardId
from .board import BoardCollocationsByBoardId, BoardCollocationsExtractByBoardId
from .board import BoardAnalizeByBoardIdPretty, BoardCollocationsByBoardIdPretty