# Generated by Django 2.0.1 on 2018-01-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(default='', max_length=200),
        ),
    ]
