# Generated by Django 2.0.1 on 2018-01-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180127_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.Board')),
            ],
            options={
                'ordering': ('-board_id',),
            },
        ),
    ]
