# Generated by Django 2.0.1 on 2018-01-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardanalyze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('sentence', models.TextField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_keyword', to='board.Board')),
            ],
            options={
                'ordering': ('-board_id',),
            },
        ),
    ]
